### ISSUE TITLE
Is that possible to use this code to export obj/stl/fbx files?

### ISSUE THREAD

**Issue by hanspond** [CalciferZh/SMPL-AMC-Imitator#1]
Hi, I'm trying to use this code to generate fbx files as SMPL.
Is there a more detailed explanation on this code?

**Comment by CalciferZh** [comment]
By now only exporting .obj file is supported. I'll update README later.

**Comment by CalciferZh** [comment]
README has been updated. Please check [here](https://github.com/CalciferZh/SMPL-AMC-Imitator#step-by-step-tutorial).
