### ISSUE TITLE
why the SMPL pose looks a little shaky? 

### ISSUE THREAD

**Issue by piaozhx** [CalciferZh/SMPL-AMC-Imitator#2]
I download the code and run `test_skeleton()` in `3DViewer.py` and find smpl skeleton is shaky. 
Is it a numerical precision problem?

**Comment by CalciferZh** [comment]
I guess it's because when transferring pose from ASF skeleton to SMPL skeleton some small errors are introduced and accumulated through the skeleton hierarchy, finally result in the visible shaking. I think numerical precision problem shouldn't be that obvious.
