### ISSUE TITLE
How to calculate 3d keypoint coordinate to SMPL pose parameters?

### ISSUE THREAD

**Issue by MikoyChinese** [CalciferZh/SMPL-AMC-Imitator#4]
Hi,
Can you tell me how to calculate 3d keypoint to smpl pose parameters, which is axis-angle. I try some way to solve it, but I can get the right pose what I want. Please help me. Thx.

**Comment by CalciferZh** [comment]
I hope [this repo](https://github.com/CalciferZh/Minimal-IK) is helpful to you. You can also further investigate the concept "inverse kinematics".

**Comment by MikoyChinese** [comment]
Thank you, I will try it.

**Comment by MikoyChinese** [comment]
Hi,
I have checked your [repo](https://github.com/CalciferZh/Minimal-IK), But I just found that it inputs a random pose to this model and fit it then return a mesh. I have no found about input 3d coordinate to get smpl pose parameters.
 
And for the inverse kinematics, I want to know the default coordinate about the original smpl model. If you have any idea about it, please help me. Thank you very much.

Have a good day!

**Comment by CalciferZh** [comment]
Sorry but I'm afraid that I cannot help more. Good luck :)
