### ISSUE TITLE
Hard to read code

### ISSUE THREAD

**Issue by SlimeVRX** [CalciferZh/SMPL-AMC-Imitator#7]
Hi @CalciferZh 

I spent 3 days reading 350 lines of code, but it was too hard to understand. Can you add an explanation on how to convert the coordinate system?

I already have background in coordinate system transformation: Euler Angle, Quaternion,...

What I'm doing is converting BVH to SMPL. I found a very interesting dataset: BEAT mocap Face (FaceID) and Body and Hand (VICON). This dataset has 70 hours, 30 actors, 8 different emotions. What impressed me most was that they built a Neural network to convert emotions when talking.

Please help me!

**Comment by CalciferZh** [comment]
Hi, sorry but I cannot remember anything about this repo. It is already five years ago.
My only vague memory is that most mocap data (maybe including BVH) use Euler angles to describe local motion. You may need to for each joint find out its axes for Euler angles, align these axes with the world coordinate frame, then convert the joint rotation from local to world. You also need to setup the correspondence between the BVH skeleton and the SMPL skeleton. 
I cannot recall any details now and I do not work in this field anymore. I'm afraid I could not help much.

**Comment by SlimeVRX** [comment]
Thanks for your advice, I'll try to keep working! If it's done, I'll report back to you.
